#!/bin/sh
### Setup
case $# in
    0) FONTSIZE="25";;
    1) FONTSIZE="$1";;
esac

if [ "$FONT_SIZE_FILE" = "" ]; then
	FONT_SIZE_FILE="/tmp/fontsize"
fi

if [ "$BIN_PATH" = "" ]; then
	BIN_PATH="$HOME/bin"
fi

if [ "$STATUSBAR_FONT" = "" ]; then
	STATUSBAR_FONT="xft:Source Code Pro:pixelsize=$FONTSIZE:antialias=true"
fi

### Main
echo BIN_PATH="$BIN_PATH"
echo FINT_SIZE_FILE="$FONT_SIZE_FILE"
echo "FONTSIZE=$FONTSIZE"

# kill old process(es)
pkill lemonbar 

# spawn new process
$BIN_PATH/statusbar_new.py | $BIN_PATH/lemonbar -f "$STATUSBAR_FONT" -p &2>/dev/null &

# save font size (used by other scripts)
echo "$FONTSIZE" > "$FONT_SIZE_FILE"

# patch st (may break running processes...)
rm $BIN_PATH/st
sed "s/pixelsize=[0-9][0-9]*/pixelsize=$FONTSIZE/g" $BIN_PATH/st_original > $BIN_PATH/st
chmod +x $BIN_PATH/st
